### ISSUE TITLE
Add verbose flag

### ISSUE THREAD

**Issue by ferhatelmas** [bloom42/flint#8]
would be nice to see what is matched/processed.

**Comment by z0mbie42** [comment]
+1
Would you think a verbose (`-v`) flag is better or a debug (`-d`) flag ?

**Comment by ferhatelmas** [comment]
`-v` seems more intuitive to me but `-d` is also totally fine. 

Since you have plenty of space, might support both.

**Comment by z0mbie42** [comment]
Hi,
As of v`2.1.0` ( ae4021e) you can use the `-v` flag to display all processed and matched files
something like
```sh
$ flint -v
./LICENSE.txt # no error
./src does not match ^[A-Z][A-Za-z\d]*$ (pascal_case) # error 
./src/error.rs does not match ^[A-Z][A-Za-z\d]*$ (pascal_case)  # error 
./src/main.rs does not match ^[A-Z][A-Za-z\d]*$ (pascal_case)  # error 
./src/rule.rs does not match ^[A-Z][A-Za-z\d]*$ (pascal_case)  # error 

$ flint
./src
./src/error.rs
./src/main.rs
./src/rule.rs
```

**Comment by ferhatelmas** [comment]
Awesome, thanks for quick taking care of it.
